# Fix OpenJDK builds
# See: https://github.com/travis-ci/travis-ci/issues/5227
# sudo: false

sudo: required
dist: trusty
group: edge
git:
  depth: false

language: java
jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk7
os:
  - linux

install: mvn -B -V -DskipTests=true -Dmaven.javadoc.skip=true install
script: mvn -B -V test
after_success:
  - if [[ $JAVA_HOME =~ java-9 ]] ; then mvn -B -V -Pcoverage clean verify sonar:sonar; fi
  - if [[ $JAVA_HOME =~ java-8 ]] ; then mvn -B -V -Pcoverage clean verify coveralls:report; fi

addons:
  apt:
    packages:
      - oracle-java9-installer
      - oracle-java8-installer
  sonarcloud:
    organization: "lviggiano-github"
    token:
      secure: "vVQbFTu1zeP+r4vZ/cDs5JAWIYEWJY0sLMuSJgZqsqZdk01aCevx2Qoyjf+LpSYLV8MO0R2ArehlIw4po2MOGk9fy6tUswlGSkm13nJesf8JK69id+8u1TH7jLB4miB0QSSz5Dy8puE9MojeKfJDDG//U+tbBKyRWO9FbFd3fVY="

